### PR TITLE
Add instruction to enable git color (fixes #1)

### LINKED ISSUE #1: Git color in tree view does not work
Git color won't show if using bliss-ui, other default ui are fine. Don't know if it's a bug or not.

Thanks for creating bliss-ui. Cheers!

### PR DESCRIPTION
**Pull request by wyudong**

### CODE REVIEW

**Comment by saadq** [comment]
Ahh, sorry I meant that in the PR you can just actually remove those styles that blocked the Git syntax highlighting. So just delete the lines that I mentioned (and the ones you mentioned).

And then, in the **Recommended Styles**, you can say to add the following to your custom stylesheet:

```sass
// Remove Git highlighting from tree view
.status-modified,
.status-added,
.status-renamed,
.status-removed {
  color: inherit;
  background-color: inherit;

  &.directory > .list-item {
    color: inherit !important;
    background-color: inherit !important;
  }

  &.directory.selected > .list-item {
    color: inherit !important;
    background-color: inherit !important;
  }
}

.tree-view {
  .icon-file-text, .icon {
    color: #c0c0c0;
  }
}
```

**Comment by wyudong** [comment]
Haha, your way is much more better. I will make another PR in a short time.

**Comment by saadq** [comment]
Sounds good, and thanks for your time!

**Comment by wyudong** [comment]
PR done and README updated. The issue exists in apex-ui too: https://github.com/apex/apex-ui/issues/26

**Comment by saadq** [comment]
Awesome work! I like the approach of changing the color of `.icon`. Thanks very much for the help on this :)

**Pull request merged**
